MODEL_FAN_V2 = "zhimi.fan.v2"  # Pedestal Fan Fan V2
MODEL_FAN_V3 = "zhimi.fan.v3"  # Pedestal Fan Fan V3
MODEL_FAN_SA1 = "zhimi.fan.sa1"  # Pedestal Fan Fan SA1
MODEL_FAN_ZA1 = "zhimi.fan.za1"  # Pedestal Fan Fan ZA1
MODEL_FAN_ZA3 = "zhimi.fan.za3"  # Pedestal Fan Fan ZA3
MODEL_FAN_ZA4 = "zhimi.fan.za4"  # Pedestal Fan Fan ZA4
MODEL_FAN_ZA5 = "zhimi.fan.za5"  # Smartmi Standing Fan 3
MODEL_FAN_P5 = "dmaker.fan.p5"  # Pedestal Fan Fan P5
MODEL_FAN_P8 = "dmaker.fan.p8"  # Pedestal Fan Fan P8
MODEL_FAN_P9 = "dmaker.fan.p9"  # Pedestal Fan Fan P9
MODEL_FAN_P10 = "dmaker.fan.p10"  # Pedestal Fan Fan P10
MODEL_FAN_P11 = "dmaker.fan.p11"  # Mijia Pedestal Fan
MODEL_FAN_P15 = "dmaker.fan.p15"  # Pedestal Fan Fan P15
MODEL_FAN_P18 = "dmaker.fan.p18"  # Mi Smart Standing Fan 2 P18
MODEL_FAN_P30 = "dmaker.fan.p30"  # Mi Smart Standing Fan 2 P30
MODEL_FAN_P33 = "dmaker.fan.p33"  # Mi Smart Standing Fan Pro 2
MODEL_FAN_P39 = "dmaker.fan.p39"  # Smart Tower Fan
MODEL_FAN_P45 = "xiaomi.fan.p45"  # Smart Tower Fan 2
MODEL_FAN_LESHOW_SS4 = "leshow.fan.ss4"
MODEL_FAN_1C = "dmaker.fan.1c"  # Pedestal Fan Fan 1C
